version: '3'
services:
  mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mosquittodata:/mosquitto/data
      - mosquittolog:/mosquitto/log

volumes:
  mosquittodata:
    driver: 'local'
  mosquittolog:
    driver: 'local'
